In [1]:
SELECT * FROM 'customer_shopping_behavior.csv';

      Customer ID  Age  ... Payment Method Frequency of Purchases
0               1   55  ...          Venmo            Fortnightly
1               2   19  ...           Cash            Fortnightly
2               3   50  ...    Credit Card                 Weekly
3               4   21  ...         PayPal                 Weekly
4               5   45  ...         PayPal               Annually
...           ...  ...  ...            ...                    ...
3895         3896   40  ...          Venmo                 Weekly
3896         3897   52  ...  Bank Transfer              Bi-Weekly
3897         3898   46  ...          Venmo              Quarterly
3898         3899   44  ...          Venmo                 Weekly
3899         3900   52  ...          Venmo              Quarterly

[3900 rows x 18 columns]

In [2]:
import pandas as pd

In [4]:
df= pd.read_csv('customer_shopping_behavior.csv')

In [5]:
df.head()

   Customer ID  Age  ... Payment Method Frequency of Purchases
0            1   55  ...          Venmo            Fortnightly
1            2   19  ...           Cash            Fortnightly
2            3   50  ...    Credit Card                 Weekly
3            4   21  ...         PayPal                 Weekly
4            5   45  ...         PayPal               Annually

[5 rows x 18 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [9]:
df.describe(include='all')

        Customer ID          Age  ... Payment Method Frequency of Purchases
count   3900.000000  3900.000000  ...           3900                   3900
unique          NaN          NaN  ...              6                      7
top             NaN          NaN  ...         PayPal         Every 3 Months
freq            NaN          NaN  ...            677                    584
mean    1950.500000    44.068462  ...            NaN                    NaN
std     1125.977353    15.207589  ...            NaN                    NaN
min        1.000000    18.000000  ...            NaN                    NaN
25%      975.750000    31.000000  ...            NaN                    NaN
50%     1950.500000    44.000000  ...            NaN                    NaN
75%     2925.250000    57.000000  ...            NaN                    NaN
max     3900.000000    70.000000  ...            NaN                    NaN

[11 rows x 18 columns]

In [10]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [16]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [17]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [18]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [19]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [20]:
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [21]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [22]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [23]:

df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [24]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [25]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [26]:
df = df.drop('promo_code_used', axis=1)

In [27]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [29]:
#I overwrite the old csv file.

df.to_csv('customer_shopping_behavior.csv', index=False)

In [31]:
select * from 'customer_shopping_behavior.csv'

      customer_id  age  ...    age_group purchase_frequency_days
0               1   55  ...  Middle-aged                      14
1               2   19  ...  Young Adult                      14
2               3   50  ...  Middle-aged                       7
3               4   21  ...  Young Adult                       7
4               5   45  ...  Middle-aged                     365
...           ...  ...  ...          ...                     ...
3895         3896   40  ...        Adult                       7
3896         3897   52  ...  Middle-aged                      14
3897         3898   46  ...  Middle-aged                      90
3898         3899   44  ...        Adult                       7
3899         3900   52  ...  Middle-aged                      90

[3900 rows x 19 columns]

In [32]:
--1. What is the total revenue generated by male vs female customer?
select gender, sum(purchase_amount) as revenue
	from 'customer_shopping_behavior.csv'
group by gender

   gender   revenue
0    Male  157890.0
1  Female   75191.0

In [36]:
--2. Which customer used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount from 'customer_shopping_behavior.csv'
where discount_applied = 'yes' and purchase_amount > (select AVG(purchase_amount) from 'customer_shopping_behavior.csv')

     customer_id  purchase_amount
0              2               64
1              3               73
2              4               90
3              7               85
4              9               97
..           ...              ...
834         1667               64
835         1671               73
836         1673               73
837         1674               62
838         1676               90

[839 rows x 2 columns]

In [40]:
--3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as avg 
	from 'customer_shopping_behavior.csv'
group by item_purchased
order by avg DESC
limit 5;

-- This quesiton is really important as these items can be sold in premium prices.

  item_purchased   avg
0         Gloves  3.86
1        Sandals  3.84
2          Boots  3.82
3            Hat  3.80
4        Handbag  3.78

In [45]:
--4. Compare the average purchase amounts between standard and express shipping.
select shipping_type, round(avg(purchase_amount),2) 
	from 'customer_shopping_behavior.csv'
	where shipping_type in ('Express', 'Standard') 
	group by shipping_type

-- My conclusion - the business should invest more on Express and faster delivery options.

  shipping_type  round(avg(purchase_amount), 2)
0       Express                           60.48
1      Standard                           58.46

In [59]:
--5. Do subscribed customers spend more? Compare average spend and total revenue between subscribed and non-subscriber?
select subscription_status, 
		count(customer_id), 
		round(avg(purchase_amount),2) as average_spend, 
		sum(purchase_amount) as total_revenue
	from 'customer_shopping_behavior.csv'
group by subscription_status
order by total_revenue;


-- No, un-subscribed customer have made purchased more by 0.38%.

   subscription_status  count(customer_id)  average_spend  total_revenue
0                 True                1053          59.49        62645.0
1                False                2847          59.87       170436.0

In [63]:
--6. Which 5 products have the highest percentage of purchases with discount applied?
select item_purchased, round(avg(purchase_frequency_days),2) from 'customer_shopping_behavior.csv'
where discount_applied = 'true' 
group by item_purchased
limit 5;

  item_purchased  round(avg(purchase_frequency_days), 2)
0        Sweater                                   79.49
1          Jeans                                  113.19
2       Sneakers                                   92.31
3          Shoes                                   87.51
4          Dress                                   85.85

1. What is the total revenue generated by male vs female customer?
2. Which customer used a discount but still spent more than the average purchase amount?
3. Which are the top 5 products with the highest average review rating?
4. Compare the average purchase amounts between standard and express shipping.
5. Do subscribed customers spend more? Compare average spend and total revenue between subscribed and non-subscriber?
6. Which 5 products have the highest percentage of purchases with doscount applied?
7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
8. What are the top 3 most purchased products within each category?
9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
10. What is the revenue contribution of each age group?